### ISSUE TITLE
No connection with Telegram

### ISSUE THREAD

**Issue by registriren** [Neolysion/WTT-Bridge#1]
2019-05-27 10:47:39,647 - src.telegram_bot - INFO - Group not found, waiting for creation...
2019-05-27 10:47:40,648 - src.telegram_bot - INFO - Group not found, waiting for creation...
2019-05-27 10:47:41,303 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "POST /bot8XXXXXX:AAXXXXXXXXX-XXXXXXXXX_XXXXXXX/getUpdates HTTP/1.1" 200 23
2019-05-27 10:47:41,304 - telegram.bot - DEBUG - No new updates found.
2019-05-27 10:47:41,304 - telegram.bot - DEBUG - []
2019-05-27 10:47:41,304 - telegram.bot - DEBUG - Exiting: get_updates
2019-05-27 10:47:41,304 - telegram.bot - DEBUG - Entering: get_updates
2019-05-27 10:47:41,649 - src.telegram_bot - INFO - Group not found, waiting for creation...
2019-05-27 10:47:42,650 - src.telegram_bot - INFO - Group not found, waiting for creation...

**Comment by s-boris** [comment]
is there a message in the log that telethon maybe failed to start or authenticate?

**Comment by registriren** [comment]
> is there a message in the log that telethon maybe failed to start or authenticate?

everything seems fine here

Nothing goes to the Telegram...

The following method bot message to the user delivers:

from telethon import TelegramClient, sync
api_id = 7XXXXX
api_hash = '5fxxxxxxxxxxxxxxxxxxxxxxxxxxxxx0b'
tg_id = 9XXXXXXX 
client = TelegramClient('anon', api_id, api_hash)
client.start()
client.send_message(tg_id, 'Hello! Talking to you from Telethon')


[log.txt](https://github.com/Neolysion/WTT-Bridge/files/3225412/log.txt)
the error occurred while receiving a message in whatsapp

**Comment by registriren** [comment]
completely updated files from the main repository, there was an error:

File "run.py", line 7, in <module>
    import src.telegram_bot as tg
  File "/root/WTT-Bridge/src/telegram_bot.py", line 6, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL' 

module PIL install -  the error remains: src.telegram_bot - INFO - Group not found, waiting for creation...
messages from Whatsapp are still not sent to Telegram and back, while in the log you can see that I write the Telegram bot

**Comment by s-boris** [comment]
Looks like I forgot to add the dependency to the requirements.txt. The PIL package is called Pillow. Try running `pip install pillow`

**Comment by registriren** [comment]
I did all this, but the transfer to Telegram never happens, I have already created a group in Telegram, added a bot to it and made it an administrator... does not help, the error persists: 
src.telegram_bot - INFO - Group not found, waiting for creation...

**Comment by s-boris** [comment]
I cleaned up and added some more logging, so we can find this bug better. Please update WTT and send me the log

**Comment by s-boris** [comment]
@registriren I just realized that I forgot to add the telethon login process to the readme. When you first started WTT you probably had to enter some login info. I assume you entered the bot token and not your phone number? 

If so you have to enter your phone number instead and then confirm it with the code you get on telegram. (WTT needs access to a bot account and your own telegram account, because bot accounts can't create groups so WTT has to use your account)

I think the telethon login is stored in the anon.session file. Try deleting that to start the login process again.

**Comment by registriren** [comment]
> @registriren I just realized that I forgot to add the telethon login process to the readme. When you first started WTT you probably had to enter some login info. I assume you entered the bot token and not your phone number?
> 
> If so you have to enter your phone number instead and then confirm it with the code you get on telegram. (WTT needs access to a bot account and your own telegram account, because bot accounts can't create groups so WTT has to use your account)
> 
> I think the telethon login is stored in the anon.session file. Try deleting that to start the login process again.

That's right, I entered the bot token. Now the shipment is working! 
What I did: 
1. Deleted non.session, but after running run.py file was created automatically and nothing to enter not offered, I re-deleted it and formed a separate team https://github.com/LonamiWebs/Telethon#creating-a-client that , I think there still needs more work. 
2. Messages from Whatsapp began to arrive in Telegram in a separate group, but the answer had to give the bot administrator rights, I think it needs to be added to readme.

There is a problem: the names of Whatsapp users written in Cyrillic are distorted into unreadable characters, they form the name of the group (for example, the name of Olya was [WA]ÐÐ"Ñ), while the text is sent in Cyrillic correctly.

**Comment by registriren** [comment]
> @registriren I just realized that I forgot to add the telethon login process to the readme. When you first started WTT you probably had to enter some login info. I assume you entered the bot token and not your phone number?
> 
> If so you have to enter your phone number instead and then confirm it with the code you get on telegram. (WTT needs access to a bot account and your own telegram account, because bot accounts can't create groups so WTT has to use your account)
> 
> I think the telethon login is stored in the anon.session file. Try deleting that to start the login process again.

That's right, I entered the bot token. Now the shipment is working! 

Messages from Whatsapp began to arrive in Telegram in a separate group, but the answer had to give the bot administrator rights, I think it needs to be added to readme.

There is a problem: the names of Whatsapp users written in Cyrillic are distorted into unreadable characters, they form the name of the group (for example, the name of "Оля" was [WA]ÐÐ"Ñ), while the text is sent in Cyrillic correctly. 
In the chatmap.json file, the name "Оля" corresponds to "[WA] \ u00d0 \ u009e \ u00d0 \ u00bb \ u00d1 \ u008f": {"waID": "79XXXXXXXXX@s.whatsapp.net", "thread": "-32XXXXXX "}}
