### ISSUE TITLE
ERROR setup.sh

### ISSUE THREAD

**Issue by registriren** [Neolysion/WTT-Bridge#8]
The first time you run setup.sh due to the absence of the ./__env/ directory, dependencies are installed in the user's directory, which later causes an error in the start.sh script

WTT-Bridge Setup
------------------
./setup.sh: line 9: python: command not found
./setup.sh: line 9: python: command not found
./setup.sh: line 9: python: command not found
./setup.sh: line 10: python3: command not found
./setup.sh: line 10: python3: command not found
Creating virtual environment for python ...
Ensuredip is not created
available. On Debian / Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt-get install python3-venv

You can use sudo with that command. After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/root/WTT-Bridge/__env/bin/python3.6', '-Im', 'ensurepip', '--upgrade', '--default-pip']

./setup.sh: line 36: ./__env/bin/activate: No such file or directory
Requirement already up-to-date: pip in /usr/local/lib/python3.6/dist-packages (19.1.1)
Requirement already satisfied: requests in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 1)) (2.22.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 2)) (4.32.1) ....

**Comment by registriren** [comment]
Additionally, it may be worth adding the presence of the config.json file in setup.sh and, if it exists, perform only a limited set of commands, without creating whatsapp keys and telegrams if they are already present in config.json

**Comment by LevinGermann** [comment]
Can you check that you have the python virtual environment module installed by running

apt-get install python3-venv

(or python3.6-venv, depends on your setup)

**Comment by registriren** [comment]
the module installed but it does not create directory ./__env/

a catalogue appeared after setup.sh but the dependencies are already installed there

**Comment by registriren** [comment]
I may have broken the installation, sorry

**Comment by LevinGermann** [comment]
No worries :)
I just see this problem happened [here](https://stackoverflow.com/questions/39539110/pyvenv-not-working-because-ensurepip-is-not-available) as well, might help you too.
